image: asmorkalov/gap_sdk:3.1

stages:
  - BuildDemo
  - BuildAndroid
  - GapuinoTest
  - Deploy

BuildDemo_GAPOC:
  stage: BuildDemo
  script: source /gap_sdk/sourceme.sh && cd ./ReID-Demo && make BOARD_NAME=gapoc_a all
  artifacts:
    paths:
      - ReID-Demo/BUILD/GAP8/GCC_RISCV/test

BuildDemo_DUMP_DESCRIPTORS:
  stage: BuildDemo
  script: source /gap_sdk/sourceme.sh && cd ./ReID-Demo && make BOARD_NAME=gapoc_a DUMP_SUCCESSFUL_FRAME=1 all
  artifacts:
    paths:
      - ReID-Demo/BUILD/GAP8/GCC_RISCV/test

BuildDemo_DUMP_DESCRIPTORS:
  stage: BuildDemo
  script: source /gap_sdk/sourceme.sh && cd ./ReID-Demo && make BOARD_NAME=gapoc_a DUMP_SUCCESSFUL_FRAME=1 all
  artifacts:
    paths:
      - ReID-Demo/BUILD/GAP8/GCC_RISCV/test

BuildDemo_GAPOC_STATIC:
  stage: BuildDemo
  script: source /gap_sdk/sourceme.sh && cd ./ReID-Demo && make BOARD_NAME=gapoc_a STATIC_FACE_DB=1 all

BuildDemo_GAPOC_STATIC_BLE:
  stage: BuildDemo
  script: source /gap_sdk/sourceme.sh && cd ./ReID-Demo && make BOARD_NAME=gapoc_a STATIC_FACE_DB=1 BLE_NOTIFIER=1 all

BuildDemo_GAPOC_STATIC_BLE_SILENT:
  stage: BuildDemo
  script: source /gap_sdk/sourceme.sh && cd ./ReID-Demo && make BOARD_NAME=gapoc_a STATIC_FACE_DB=1 BLE_NOTIFIER=1 SILENT=1 all
  artifacts:
    paths:
      - ReID-Demo/BUILD/GAP8/GCC_RISCV/test

BuildDemo_GAPUINO:
  stage: BuildDemo
  script: source /gap_sdk/sourceme.sh && cd ./ReID-Demo && make BOARD_NAME=gapuino all

SingleLayerTest:
  stage: GapuinoTest
  script: source /gap_sdk/sourceme.sh && cd ./tests/ && ln -s /test_data/activations_dump_transposed ./activations_dump && ./test_layers_one_by_one.sh -gapuino
  artifacts:
    when: on_failure
    paths:
      - tests/single_layer_test_summary.csv
      - tests/single_logs/*.log
  tags:
    - gapuino

InferenceTest:
  stage: GapuinoTest
  script: source /gap_sdk/sourceme.sh && cd ./tests/ && ln -s /test_data/activations_dump_transposed ./activations_dump && ./test_inference.sh -gapuino
  artifacts:
    when: on_failure
    paths:
      - tests/inference_test_summary.csv
      - tests/inference_logs/*.log
  tags:
    - gapuino

DbSelectorTest:
  stage: GapuinoTest
  script: source /gap_sdk/sourceme.sh && cd ./tests/db_selector_test && make run
  tags:
    - gapuino

BuildBleTest:
  stage: GapuinoTest
  script: source /gap_sdk/sourceme.sh && cd ./tests/ble_test && make all

PreparePipelineTest:
  stage: GapuinoTest
  script: source /gap_sdk/sourceme.sh && cd ./tests/ && ./test_prepare_pipeline.sh -gapuino
  artifacts:
    when: on_failure
    paths:
      - tests/prepare_pipeline_logs/*
  tags:
    - gapuino

BuildAndroidNotifier:
  stage: BuildAndroid
  image: registry.gitlab.com/xperience-ai/gap/facereid
  script:
    - cd AndroidNotifier
    - gradle assemble
    - cp app/build/outputs/apk/debug/app-debug.apk ../ReID-Speaker-latest.apk
  artifacts:
    paths:
    - ReID-Speaker-latest.apk

BuildAndroidControlPanel:
  stage: BuildAndroid
  image: registry.gitlab.com/xperience-ai/gap/facereid
  script:
    - cd AndroidControlPanel
    - gradle assemble
    - cp app/build/outputs/apk/debug/app-debug.apk ../ReID-Control-App-latest.apk
  artifacts:
    paths:
      - ReID-Control-App-latest.apk

Deploy:
  stage: Deploy
  script:
    - mkdir deploy && cd deploy && rm -rf *
    - tar -cj --file activations_dump.tar.bz2 /test_data/activations_dump_transposed/*
    - mv ../ReID-Speaker-latest.apk ./
    - mv ../ReID-Control-App-latest.apk ./
    - rclone --config $RCLONE_S3_CONFIG sync -P activations_dump.tar.bz2 reid_s3:"face-reid-artifacts/FaceID/"
    - rclone --config $RCLONE_S3_CONFIG sync -P ReID-Speaker-latest.apk reid_s3:"face-reid-artifacts/FaceID/"
    - rclone --config $RCLONE_S3_CONFIG sync -P ReID-Control-App-latest.apk reid_s3:"face-reid-artifacts/FaceID/"
    - rclone --config $RCLONE_GDRIVE_CONFIG sync -P activations_dump.tar.bz2 gdrive:"Xperience.ai/Projects/Greenwaves-public"
    - rclone --config $RCLONE_GDRIVE_CONFIG sync -P ReID-Speaker-latest.apk gdrive:"Xperience.ai/Projects/Greenwaves-public"
    - rclone --config $RCLONE_GDRIVE_CONFIG sync -P ReID-Control-App-latest.apk gdrive:"Xperience.ai/Projects/Greenwaves-public"
  image: registry.gitlab.com/xperience-ai/gap/facereid
  tags:
    - gapuino
  only:
    refs:
      - master
