image: asmorkalov/gap_sdk:3.2

stages:
  - BuildDemo
  - BuildAndroid
  - GapuinoTest
  - Deploy

BuildDemo_GAPOC:
  stage: BuildDemo
  script:
    - source /gap_sdk/configs/gapoc_a_v2.sh
    - cd ReID-Demo
    - make all
    - make all | grep 'Nothing to be done'
  artifacts:
    paths:
      - ReID-Demo/BUILD/GAP8_V2/GCC_RISCV/test

BuildDemo_DUMP_DESCRIPTORS:
  stage: BuildDemo
  script:
    - source /gap_sdk/configs/gapuino_v2.sh
    - cd ./ReID-Demo
    - make DUMP_SUCCESSFUL_FRAME=1 all
  artifacts:
    paths:
      - ReID-Demo/BUILD/GAP8/GCC_RISCV/test

BuildDemo_GAPOC_STATIC:
  stage: BuildDemo
  script:
    - source /gap_sdk/configs/gapoc_a_v2.sh
    - cd ./ReID-Demo
    - make STATIC_FACE_DB=1 all

BuildDemo_GAPOC_STATIC_BLE:
  stage: BuildDemo
  script:
    - source /gap_sdk/configs/gapoc_a_v2.sh
    - cd ./ReID-Demo
    - make STATIC_FACE_DB=1 BLE_NOTIFIER=1 all

BuildDemo_GAPOC_STATIC_BLE_SILENT:
  stage: BuildDemo
  script:
    - source /gap_sdk/configs/gapoc_a_v2.sh
    - cd ./ReID-Demo
    - make STATIC_FACE_DB=1 BLE_NOTIFIER=1 SILENT=1 all
  artifacts:
    paths:
      - ReID-Demo/BUILD/GAP8_V2/GCC_RISCV/test

BuildDemo_GAPUINO:
  stage: BuildDemo
  script:
    - source /gap_sdk/configs/gapuino_v2.sh
    - cd ReID-Demo
    - make all
    - make all | grep 'Nothing to be done'

SingleLayerTest:
  stage: GapuinoTest
  script:
    - source /gap_sdk/configs/$BOARD_NAME.sh
    - cd ./tests/
    - ln -s /test_data/activations_dump_bn ./activations_dump
    - ./test_layers_one_by_one.sh
  artifacts:
    when: on_failure
    paths:
      - tests/single_layer_test_summary.csv
      - tests/single_logs/*.log
  tags:
    - GAP8v2

InferenceTest:
  stage: GapuinoTest
  script:
    - source /gap_sdk/configs/$BOARD_NAME.sh
    - cd ./tests/
    - ln -s /test_data/activations_dump_bn ./activations_dump
    - ./test_inference.sh
  artifacts:
    when: on_failure
    paths:
      - tests/inference_test_summary.csv
      - tests/inference_logs/*.log
  tags:
    - GAP8v2

InferenceTest_SILENT:
  stage: GapuinoTest
  script:
    - source /gap_sdk/configs/$BOARD_NAME.sh
    - cd ./tests/
    - ln -s /test_data/activations_dump_bn ./activations_dump
    - ./test_inference.sh SILENT=1
  artifacts:
    when: on_failure
    paths:
      - tests/inference_test_summary.csv
      - tests/inference_logs/*.log
  tags:
    - GAP8v2

DbSelectorTest:
  stage: GapuinoTest
  script:
    - source /gap_sdk/configs/$BOARD_NAME.sh
    - cd ./tests/db_selector_test
    - make run
  tags:
    - GAP8v2

DbSelectorTest_SILENT:
  stage: GapuinoTest
  script:
    - source /gap_sdk/configs/$BOARD_NAME.sh
    - cd ./tests/db_selector_test
    - make SILENT=1 run
  tags:
    - GAP8v2

BuildBleTest:
  stage: GapuinoTest
  script: source /gap_sdk/configs/gapoc_a_v2.sh
    - cd ./tests/ble_test
    - make all

PreparePipelineTest:
  stage: GapuinoTest
  script:
    source /gap_sdk/configs/$BOARD_NAME.sh
    - cd ./tests/
    - ./test_prepare_pipeline.sh
  artifacts:
    when: on_failure
    paths:
      - tests/prepare_pipeline_logs/*
  tags:
    - GAP8v2

PreparePipelineTest_SILENT:
  stage: GapuinoTest
  script:
    - source /gap_sdk/configs/$BOARD_NAME.sh
    - cd ./tests/
    - ./test_prepare_pipeline.sh SILENT=1
  artifacts:
    when: on_failure
    paths:
      - tests/prepare_pipeline_logs/*
  tags:
    - GAP8v2

ReIDPipelineTest:
  stage: GapuinoTest
  script:
    - source /gap_sdk/configs/$BOARD_NAME.sh
    - cd ./ReID-Demo
    - make clean reid_model
    - cd ../tests/reid_pipeline_test
    - make run | tee test.log
    - "grep 'Hi, Lena! Conf: 0' test.log"
  tags:
    - GAP8v2

ReIDPipelineTest_SILENT:
  stage: GapuinoTest
  script:
    - source /gap_sdk/configs/$BOARD_NAME.sh
    - cd ./ReID-Demo
    - make clean reid_model
    - cd ../tests/reid_pipeline_test
    - make SILENT=1 run | tee test.log
    - "grep 'Hi, Lena! Conf: 0' test.log"
  tags:
    - GAP8v2


BuildAndroidNotifier:
  stage: BuildAndroid
  image: registry.gitlab.com/xperience-ai/gap/facereid
  script:
    - cd AndroidNotifier
    - gradle assemble
    - cp app/build/outputs/apk/debug/app-debug.apk ../ReID-Speaker-latest.apk
  artifacts:
    paths:
    - ReID-Speaker-latest.apk

BuildAndroidControlPanel:
  stage: BuildAndroid
  image: registry.gitlab.com/xperience-ai/gap/facereid
  script:
    - cd AndroidControlPanel
    - gradle assemble
    - cp app/build/outputs/apk/debug/app-debug.apk ../ReID-Control-App-latest.apk
  artifacts:
    paths:
      - ReID-Control-App-latest.apk

Deploy:
  stage: Deploy
  script:
    - mkdir deploy
    - cd deploy
    - rm -rf *
    - tar -cj --file activations_dump.tar.bz2 /test_data/activations_dump_bn/*
    - mv ../ReID-Speaker-latest.apk ./
    - mv ../ReID-Control-App-latest.apk ./
    - rclone --config $RCLONE_S3_CONFIG sync -P activations_dump.tar.bz2 reid_s3:"face-reid-artifacts/FaceID/"
    - rclone --config $RCLONE_S3_CONFIG sync -P ReID-Speaker-latest.apk reid_s3:"face-reid-artifacts/FaceID/"
    - rclone --config $RCLONE_S3_CONFIG sync -P ReID-Control-App-latest.apk reid_s3:"face-reid-artifacts/FaceID/"
    - rclone --config $RCLONE_GDRIVE_CONFIG sync -P activations_dump.tar.bz2 gdrive:"Xperience.ai/Projects/Greenwaves-public"
    - rclone --config $RCLONE_GDRIVE_CONFIG sync -P ReID-Speaker-latest.apk gdrive:"Xperience.ai/Projects/Greenwaves-public"
    - rclone --config $RCLONE_GDRIVE_CONFIG sync -P ReID-Control-App-latest.apk gdrive:"Xperience.ai/Projects/Greenwaves-public"
  image: registry.gitlab.com/xperience-ai/gap/facereid
  tags:
    - gapuino
  only:
    refs:
      - master
