/*
 * Copyright 2019 GreenWaves Technologies, SAS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "param_layer_struct.h"

struct param_conv_layer convLayers[] =
{
    // Intro convolutions
    {.nb_if = 1,
     .nb_of = 3,
     .win = 128,
     .hin = 128,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 0,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 0,
     .q_out = 13,
     .q_w = 20,
     .q_b = 13,
     .name = "conv1.0"},

    {.nb_if = 3,
     .nb_of = 64,
     .win = 128,
     .hin = 128,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .conv_padding = 0,
     .conv_stride = 2,
     .q_in = 13,
     .q_out = 11,
     .q_w = 14,
     .q_b = 11,
     .name = "features.0.0"},

    // Fire modules
    {.nb_if = 64,
     .nb_of = 16,
     .win = 31,
     .hin = 31,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 11,
     .q_out = 11,
     .q_w = 14,
     .q_b = 11,
     .name = "features.3.squeeze.0"},

    {.nb_if = 16,
     .nb_of = 64,
     .win = 31,
     .hin = 31,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 11,
     .q_out = 12,
     .q_w = 14,
     .q_b = 12,
     .name = "features.3.expand1x1.0"},

    {.nb_if = 16,
     .nb_of = 64,
     .win = 31,
     .hin = 31,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 11,
     .q_out = 12,
     .q_w = 15,
     .q_b = 12,
     .name = "features.3.expand3x3.0"},

    {.nb_if = 128,
     .nb_of = 16,
     .win = 31,
     .hin = 31,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 12,
     .q_out = 12,
     .q_w = 14,
     .q_b = 12,
     .name = "features.4.squeeze.0"},

    {.nb_if = 16,
     .nb_of = 64,
     .win = 31,
     .hin = 31,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 12,
     .q_out = 12,
     .q_w = 15,
     .q_b = 12,
     .name = "features.4.expand1x1.0"},

    {.nb_if = 16,
     .nb_of = 64,
     .win = 31,
     .hin = 31,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 12,
     .q_out = 12,
     .q_w = 16,
     .q_b = 12,
     .name = "features.4.expand3x3.0"},

    // MaxPool here

    {.nb_if = 128,
     .nb_of = 32,
     .win = 15,
     .hin = 15,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 12,
     .q_out = 13,
     .q_w = 16,
     .q_b = 13,
     .name = "features.6.squeeze.0"},

    {.nb_if = 32,
     .nb_of = 128,
     .win = 15,
     .hin = 15,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 13,
     .q_out = 13,
     .q_w = 15,
     .q_b = 13,
     .name = "features.6.expand1x1.0"},

    {.nb_if = 32,
     .nb_of = 128,
     .win = 15,
     .hin = 15,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 13,
     .q_out = 13,
     .q_w = 16,
     .q_b = 13,
     .name = "features.6.expand3x3.0"},

    {.nb_if = 256,
     .nb_of = 32,
     .win = 15,
     .hin = 15,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 13,
     .q_out = 13,
     .q_w = 15,
     .q_b = 13,
     .name = "features.7.squeeze.0"},

    {.nb_if = 32,
     .nb_of = 128,
     .win = 15,
     .hin = 15,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 13,
     .q_out = 13,
     .q_w = 16,
     .q_b = 13,
     .name = "features.7.expand1x1.0"},

    {.nb_if = 32,
     .nb_of = 128,
     .win = 15,
     .hin = 15,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 13,
     .q_out = 13,
     .q_w = 16,
     .q_b = 13,
     .name = "features.7.expand3x3.0"},

    // MaxPool here

    {256,48,7,7,1,1, 1, 0,0,0, 1,1, 13,13,15,13, "features.9.squeeze.0"},
    {48,192,7,7,1,1, 1, 0,0,0, 1,1, 13,14,16,14, "features.9.expand1x1.0"},
    {48,192,7,7,3,3, 1, 0,0,0, 1,1, 13,14,17,14, "features.9.expand3x3.0"},

    {384,48,7,7,1,1, 1, 0,0,0, 1,1, 14,13,14,13, "features.10.squeeze.0"},
    {48,192,7,7,1,1, 1, 0,0,0, 1,1, 13,13,16,13, "features.10.expand1x1.0"},
    {48,192,7,7,3,3, 1, 0,0,0, 1,1, 13,13,16,13, "features.10.expand3x3.0"},

    {384,64,7,7,1,1, 1, 0,0,0, 1,1, 13,13,14,13, "features.11.squeeze.0"},
    {64,256,7,7,1,1, 1, 0,0,0, 1,1, 13,14,16,14, "features.11.expand1x1.0"},
    {64,256,7,7,3,3, 1, 0,0,0, 1,1, 13,14,17,14, "features.11.expand3x3.0"},

    {.nb_if = 512,
     .nb_of = 64,
     .win = 7,
     .hin = 7,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 14,
     .q_out = 13,
     .q_w = 13,
     .q_b = 13,
     .name = "features.12.squeeze.0"},

    {.nb_if = 64,
     .nb_of = 256,
     .win = 7,
     .hin = 7,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 13,
     .q_out = 10,
     .q_w = 12,
     .q_b = 10,
     .name = "features.12.expand1x1.0"},

    {.nb_if = 64,
     .nb_of = 256,
     .win = 7,
     .hin = 7,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .conv_padding = 1,
     .conv_stride = 1,
     .q_in = 13,
     .q_out = 10,
     .q_w = 13,
     .q_b = 10,
     .name = "features.12.expand3x3.0"},
};
