/*
 * Copyright 2019 GreenWaves Technologies, SAS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "param_layer_struct.h"
#include "norm_list.h"

struct param_conv_layer convLayers[] =
{
    // Intro convolutions
    {.nb_if = 1,
     .nb_of = 3,
     .win = 128,
     .hin = 128,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 0,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_0,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "conv1"},

    {.nb_if = 3,
     .nb_of = 64,
     .win = 128,
     .hin = 128,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .norm_data = NORM_1,
     .conv_padding = 0,
     .conv_stride = 2,
     .name = "features.0"},

    // Fire modules
    {.nb_if = 64,
     .nb_of = 16,
     .win = 31,
     .hin = 31,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_2,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.3.squeeze"},

    {.nb_if = 16,
     .nb_of = 64,
     .win = 31,
     .hin = 31,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_3,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.3.expand1x1"},

    {.nb_if = 16,
     .nb_of = 64,
     .win = 31,
     .hin = 31,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_4,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.3.expand3x3"},

    {.nb_if = 128,
     .nb_of = 16,
     .win = 31,
     .hin = 31,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_5,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.4.squeeze"},

    {.nb_if = 16,
     .nb_of = 64,
     .win = 31,
     .hin = 31,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .norm_data = NORM_6,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.4.expand1x1"},

    {.nb_if = 16,
     .nb_of = 64,
     .win = 31,
     .hin = 31,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .norm_data = NORM_7,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.4.expand3x3"},

    // MaxPool here

    {.nb_if = 128,
     .nb_of = 32,
     .win = 15,
     .hin = 15,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_8,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.6.squeeze"},

    {.nb_if = 32,
     .nb_of = 128,
     .win = 15,
     .hin = 15,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_9,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.6.expand1x1"},

    {.nb_if = 32,
     .nb_of = 128,
     .win = 15,
     .hin = 15,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_10,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.6.expand3x3"},

    {.nb_if = 256,
     .nb_of = 32,
     .win = 15,
     .hin = 15,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_11,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.7.squeeze"},

    {.nb_if = 32,
     .nb_of = 128,
     .win = 15,
     .hin = 15,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .norm_data = NORM_12,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.7.expand1x1"},

    {.nb_if = 32,
     .nb_of = 128,
     .win = 15,
     .hin = 15,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 1,
     .pool_size = 3,
     .pool_stride = 2,
     .norm_data = NORM_13,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.7.expand3x3"},

    // MaxPool here

    {256,48,7,7,1,1,1,0,0,0,NORM_14,1,1, "features.9.squeeze"},
    {48,192,7,7,1,1,1,0,0,0,NORM_15,1,1, "features.9.expand1x1"},
    {48,192,7,7,3,3,1,0,0,0,NORM_16,1,1, "features.9.expand3x3"},

    {384,48,7,7,1,1,1,0,0,0,NORM_17,1,1, "features.10.squeeze"},
    {48,192,7,7,1,1,1,0,0,0,NORM_18,1,1, "features.10.expand1x1"},
    {48,192,7,7,3,3,1,0,0,0,NORM_19,1,1, "features.10.expand3x3"},

    {384,64,7,7,1,1,1,0,0,0,NORM_20,1,1, "features.11.squeeze"},
    {64,256,7,7,1,1,1,0,0,0,NORM_21,1,1, "features.11.expand1x1"},
    {64,256,7,7,3,3,1,0,0,0,NORM_22,1,1, "features.11.expand3x3"},

    {.nb_if = 512,
     .nb_of = 64,
     .win = 7,
     .hin = 7,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_23,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.12.squeeze"},

    {.nb_if = 64,
     .nb_of = 256,
     .win = 7,
     .hin = 7,
     .kernel_width = 1,
     .kernel_height = 1,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_24,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.12.expand1x1"},

    {.nb_if = 64,
     .nb_of = 256,
     .win = 7,
     .hin = 7,
     .kernel_width = 3,
     .kernel_height = 3,
     .relu = 1,
     .max_pool = 0,
     .pool_size = 0,
     .pool_stride = 0,
     .norm_data = NORM_25,
     .conv_padding = 1,
     .conv_stride = 1,
     .name = "features.12.expand3x3"},
};
